name: movietrack
description: "Manage your movie watchlist."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  http: ^1.2.2
  logger: ^2.4.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  dio: ^5.7.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
